In [24]:
import numpy as np
import sys

import elastic_rods
from linkage_vis import LinkageViewer

l = elastic_rods.RodLinkage('../examples/hyperboloid_open.obj')
mat = elastic_rods.RodMaterial('+', 20000, 0.3, [0.05, 0.05, 0.001, 0.001])
l.setMaterial(mat)
l.joint(16).setConstrained(True)

restLenBound = 0.5 * l.minRestLength()
def applyRestLenBounds(edofs):
    result = edofs.copy()
    for var in l.lengthVars(True):
        result[var] = np.clip(edofs[var], restLenBound, None)
    return result

edofs = l.getExtendedDoFs()
nstep = elastic_rods.restlen_newton_step(l, laplacianRegWeight=1e-3)
nstep
def reportEnergy():
    print(l.restLengthLaplacianEnergy(), l.energyBend(), l.energyStretch(), l.energyTwist(), l.energy())

In [25]:
l.setExtendedDoFs(applyRestLenBounds(edofs + 1e-1 * nstep))
reportEnergy()
#view.update()

51.97715325446524 76080658.93722048 37629.112277053624 0.0016277520866119395 76118288.0511253


In [26]:
l.setExtendedDoFs(edofs)
reportEnergy()

0.06514808536918511 6.364724619154198e-10 0.4133914954051914 9.851808385818973e-07 0.4133924812225026


In [27]:
j = l.joint(16)
r = l.segment(30).rod
r.thetas()

[-0.30547452924883733,
 -0.2612975792014763,
 -0.2171201109828863,
 -0.17294264276429644,
 -0.1287651745457064,
 -0.08458770632711637,
 -0.040410238108526356,
 0.0037672301100634548,
 0.047944698328653106,
 0.09212216654724309]

In [129]:
l.segment(30).rod.deformedPoints()

[array([ -0.32221161, -20.94419714,   5.03502237]),
 array([ -0.36011839, -20.93040286,   4.96497763]),
 array([ -0.28430417, -20.958     ,   5.10506833]),
 array([ -0.24639694, -20.9718    ,   5.17511389]),
 array([ -0.20848972, -20.9856    ,   5.24515944]),
 array([ -0.1705825, -20.9994   ,   5.315205 ]),
 array([ -0.13267528, -21.0132    ,   5.38525056]),
 array([ -0.09476806, -21.027     ,   5.45529611]),
 array([ -0.05686083, -21.0408    ,   5.52534167]),
 array([-1.89535895e-02, -2.10546007e+01,  5.59538708e+00]),
 array([ 1.89535895e-02, -2.10683993e+01,  5.66543292e+00])]

In [105]:
l.segment(29).startJoint

16

In [100]:
[(i, s.rod.energy()) for i, s in enumerate(l.segments())]

[(0, 8.271874642034696e-09),
 (1, 2072401.2857577929),
 (2, 431716.3309440124),
 (3, 677229.0442884455),
 (4, 909105.288027297),
 (5, 910570.5468154164),
 (6, 627799.1905152007),
 (7, 970930.1222552815),
 (8, 40185.74948999526),
 (9, 4763523.45068222),
 (10, 1377010.1714586574),
 (11, 1309804.6385049063),
 (12, 8297132.185074966),
 (13, 10219448.461110324),
 (14, 1712378.0990431532),
 (15, 817699.063107477),
 (16, 8578.386424038279),
 (17, 36644.34635086983),
 (18, 44.427523700405835),
 (19, 293627.7618431746),
 (20, nan),
 (21, nan),
 (22, 498873.14589335944),
 (23, 50.89205722047173),
 (24, 946997.9963814666),
 (25, 0.016244373188395663),
 (26, 36644.346329765875),
 (27, 44.42752390194182),
 (28, 293627.76373533584),
 (29, nan),
 (30, nan),
 (31, 498873.152348888),
 (32, 50.892056542730934),
 (33, 946998.009673955),
 (34, 0.016244373105019357),
 (35, 40185.75054326786),
 (36, 4763526.024351004),
 (37, 1377010.3269044512),
 (38, 1309804.766078091),
 (39, 8297136.268498758),
 (40, 1021

In [28]:
l.setExtendedDoFs(okLinkageEDoFs)
l.energy()

NameError: name 'okLinkageEDoFs' is not defined

In [148]:
l.setDoFs(okLinkageDoFs)
l.energy()

85901875.7078737

In [149]:
l.setExtendedDoFs(badLinkageEDofs)

In [150]:
l.energy()

85901546.35679588

In [123]:
okLinkageDoFs = l.getDoFs()
okLinkageEDoFs = l.getExtendedDoFs()

In [126]:
badLinkageDoFs = l.getDoFs()
badLinkageEDofs = l.getExtendedDoFs()

In [108]:
l.saveVisualizationGeometry('test.msh')

In [125]:
l.restLengthLaplacianEnergy(), l.energyBend(), l.energyStretch(), l.energyTwist(), l.energy()

(18.311503316862908, nan, 12199.0478000419, nan, nan)

In [ ]:
[(i, s.rod.energyBend()) for i, s in enumerate(l.segments())]

In [111]:
r = l.segment(30).rod

In [97]:
dc = r.deformedConfiguration()

In [120]:
dc.materialFrame

[{ d1: [ 0.814328 -0.296334 -0.499056], d2: [  0.341962   0.939714 1.8741e-09] },
 { d1: [ 0.815264 -0.295805  -0.49784], d2: [   0.339323    0.940664 -0.00324378] },
 { d1: [ 0.816054 -0.291771 -0.498925], d2: [  0.337814   0.941211 0.00211729] },
 { d1: [ 0.819523  -0.28179 -0.498976], d2: [  0.329332   0.944183 0.00768349] },
 { d1: [ 0.826031 -0.262538 -0.498745], d2: [ 0.312652  0.949699 0.0179014] },
 { d1: [ 0.835986 -0.230739 -0.497882], d2: [ 0.284963  0.957916 0.0345394] },
 { d1: [ 0.849084 -0.182962 -0.495562], d2: [  0.24317  0.968176 0.0591894] },
 { d1: [ 0.863849  -0.11566 -0.490293], d2: [  0.18395    0.9785 0.0932741] },
 { d1: [ 0.877083 -0.025384 -0.479669], d2: [0.103913 0.984983 0.137882] },
 { d1: [ 0.883217 0.0906575 -0.460119], d2: [-7.93234e-06      0.98114     0.193299] }]

In [119]:
dc.sourceTangent

[array([ 0.46896982, -0.17065819,  0.86656973]),
 array([ 0.46896156, -0.17075828,  0.86655448]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896431, -0.17072492,  0.86655956]),
 array([ 0.46896458, -0.17073331,  0.86655776]),
 array([ 0.46896378, -0.17070815,  0.86656316])]

In [118]:
dc.tangent

[array([ 0.46896982, -0.17065819,  0.86656973]),
 array([ 0.46925969, -0.16628422,  0.86726288]),
 array([ 0.46897542, -0.17027152,  0.86664276]),
 array([ 0.46895951, -0.17062537,  0.86658177]),
 array([ 0.46895823, -0.17072095,  0.86656363]),
 array([ 0.46895961, -0.17075229,  0.86655671]),
 array([ 0.46896142, -0.17076235,  0.86655375]),
 array([ 0.46896315, -0.17076424,  0.86655244]),
 array([ 0.46896517, -0.17077764,  0.86654871]),
 array([ 0.46896481, -0.17072165,  0.86655994])]

In [101]:
okDoFs = r.getDoFs()

In [117]:
r.energy()

0.0788467467601944

In [116]:
r.setDoFs(okDoFs)

In [79]:
r.writeDebugData('test_rod.msh')

In [74]:
rview = LinkageViewer(r)
rview.show()

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(3.0, 5.0,…

In [64]:
view = LinkageViewer(l, width=768, labelOffset=-0.5)
view.setCameraParams(((0.21363949107371888, -1.5745838914291204, 3.221274247846029),
 (-0.39958918133000937, -0.9163352741275177, -0.02565446459509408),
 (-0.395065608121624, 0.38240522741182065, 0.06716453768425666)))
view.show()

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.6, positio…

In [7]:
l.getRestLengths()

array([0.19830846, 0.19830846, 0.19830846, 0.19830846, 0.19830846,
       0.19830846, 0.19830846, 0.19830846, 0.19831142, 0.19831137,
       0.19831128, 0.19831115, 0.19831099, 0.1983108 , 0.19831057,
       0.1983103 , 0.19831116, 0.1983111 , 0.19831101, 0.19831089,
       0.19831073, 0.19831053, 0.1983103 , 0.19831004, 0.19831147,
       0.19831142, 0.19831133, 0.1983112 , 0.19831104, 0.19831085,
       0.19831062, 0.19831035, 0.19831115, 0.1983111 , 0.19831101,
       0.19831089, 0.19831073, 0.19831053, 0.1983103 , 0.19831004,
       0.19831115, 0.1983111 , 0.19831101, 0.19831089, 0.19831073,
       0.19831053, 0.1983103 , 0.19831003, 0.19831147, 0.19831142,
       0.19831133, 0.1983112 , 0.19831104, 0.19831085, 0.19831062,
       0.19831035, 0.19831121, 0.19831115, 0.19831105, 0.19831091,
       0.19831074, 0.19831052, 0.19831026, 0.19830997, 0.10551646,
       0.10551645, 0.10551643, 0.10551639, 0.10551635, 0.1055163 ,
       0.10551624, 0.10551617, 0.10552152, 0.10552168, 0.10552